FROM node:20-slim AS build
WORKDIR /app
COPY package.json ./
RUN npm config set strict-ssl false && npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default.conf.template
ENV BACKEND_HOST=backend
ENV BACKEND_PORT=8080
EXPOSE 80
